[metadata]
format = { version = "1.1" }

[versions]
indra = "3.1.3"
junit = "5.10.0"
mammoth = "1.3.1"

[libraries]
githubApi = { module = "org.kohsuke:github-api", version = "1.316"}
jetbrainsAnnotations = { module = "org.jetbrains:annotations", version = "24.0.1"}
mammoth = { module = "net.kyori:mammoth", version.ref = "mammoth" }

# testing
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launrcher = { module = "org.junit.platform:junit-platform-launcher" }
mammoth-test = { module = "net.kyori:mammoth-test", version.ref = "mammoth" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-gradlePluginPublish = { id = "net.kyori.indra.publishing.gradle-plugin", version.ref = "indra" }
indra-licenserSpotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
spotless = { id = "com.diffplug.spotless", version = "6.21.0" }
pluginPublish = { id = "com.gradle.plugin-publish", version = "1.2.1" }
