[metadata]
format = { version = "1.1" }

[versions]
indra = "4.1.0"
junit = "5.13.4"
mammoth = "1.5.0"

[libraries]
githubApi = { module = "org.kohsuke:github-api", version = "1.330"}
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }
mammoth = { module = "net.kyori:mammoth", version.ref = "mammoth" }

# testing
junit-api = { module = "org.junit.jupiter:junit-jupiter-api" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }
junit-launcher = { module = "org.junit.platform:junit-platform-launcher" }
mammoth-test = { module = "net.kyori:mammoth-test", version.ref = "mammoth" }

[plugins]
indra = { id = "net.kyori.indra", version.ref = "indra" }
indra-gradlePluginPublish = { id = "net.kyori.indra.publishing.gradle-plugin", version.ref = "indra" }
indra-licenserSpotless = { id = "net.kyori.indra.licenser.spotless", version.ref = "indra" }
spotless = { id = "com.diffplug.spotless", version = "8.10.2" }
pluginPublish = { id = "com.gradle.plugin-publish", version = "2.1.1" }
