name: "build"

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:

jobs:
  call-build:
    uses: "KyoriPowered/.github/.github/workflows/shared-ci.yaml@trunk"
    permissions:
        actions: write
        contents: write
    secrets:
      STELLARDRIFT_USERNAME: ${{ secrets.STELLARDRIFT_USERNAME }}
      STELLARDRIFT_PASSWORD: ${{ secrets.STELLARDRIFT_PASSWORD }}
